### PR TITLE
Try to fix random failure

### PR DESCRIPTION
**Pull request by vmanilo**
We have issue with not stable acceptance tests, which periodically randomly fails, this PR is a follow up attempt to improve and stabilise tests.

## Changes
- updated acc test

### CODE REVIEW

**Review by ekampf — CHANGES_REQUESTED** [review]
You added a second wait between any call to server. 
Its incorrect.

The only issue we have is when a resource is read immediately after its being written.
We need to find those cases and fix those, and not just add a second delay before any network operation.

**Comment by vmanilo** [comment]
@ekampf I've addressed the issue you mentioned, checked matrix tests on my fork - looks good

**Review by ekampf — APPROVED** [review]
Lets reduce `waitForResourceAvailability()` from `1s` to half a second
Fix and merge

**Comment by ekampf** [comment]
Lets also change integration tests to run every 10m so we see they're stable

**Pull request merged**
